# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

language: R
sudo: false
cache: packages
